# Generated by Django 2.2 on 2020-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200808_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='task_set', to='webapp.Type', verbose_name='Types'),
        ),
    ]
