# Generated by Django 2.2 on 2020-08-11 19:21

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detailed_desc',
            field=models.TextField(blank=True, max_length=1500, null=True, validators=[webapp.validators.at_least_200], verbose_name='Detailed description'),
        ),
    ]
